---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: win2k12r2
    driver_config:
      box: win2k12r2
suites:
  - name: default
    run_list:
      - recipe[windows_base::default]
    attributes:
