name 'windows_base'
maintainer 'Matt Stratton'
maintainer_email 'mattstratton@chef.io'
license 'apache2'
description 'Installs/Configures windows_base'
long_description 'Installs/Configures windows_base'
version '0.1.0'

depends 'chef-client', '~> 4.3.0'
depends 'powershell', '~> 3.1.0'
